export const IMAGES = {
  eye_open: require('../assets/images/eyeopen.png'),
  eye_closed: require('../assets/images/eyeclosed.png'),
  login_background: require('../assets/images/loginBackground.png'),
  close_icon: require('../assets/images/closeIcon.png'),
  back_icon: require('../assets/images/backIcon.png'),
  silver_metal: require('../assets/images/silverMetal.png'),
  gold_metal: require('../assets/images/goldMetal.png'),
  home_color: require('../assets/images/homeColor.png'),
  home: require('../assets/images/home.png'),
  chits_color: require('../assets/images/chitsColor.png'),
  chits: require('../assets/images/chits.png'),
  transactions_color: require('../assets/images/transactionsColor.png'),
  transactions: require('../assets/images/transactions.png'),
  profile_color: require('../assets/images/profileColor.png'),
  profile: require('../assets/images/profile.png'),
  notify: require('../assets/images/notifyIcon.png'),
  filter: require('../assets/images/filterIcon.png'),
  calendar: require('../assets/images/calendarIcon.png'),
  chev_left: require('../assets/images/chev_left.png'),
  chev_right: require('../assets/images/chev_right.png'),
  diamond_metal: require('../assets/images/diamondMetal.png'),
  profile_avatar: require('../assets/images/profileAvatar.png'),
  offline: require('../assets/images/offlinenotice.png'),
};
